# Generated by Django 4.2.1 on 2023-10-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_auto_20231008_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='algocode_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='standings',
            name='disable_contest_marks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('AC', 'Acm'), ('AO', 'Acm competition'), ('OL', 'Olympiad'), ('BS', 'Battleship'), ('BT', 'Blitz')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='contest',
            name='judge',
            field=models.CharField(choices=[('EJ', 'Ejudge'), ('CF', 'Codeforces'), ('IN', 'Informatics'), ('EC', 'Ejudge cache'), ('PC', 'PCMS'), ('AG', 'Algocode')], default='EJ', max_length=2),
        ),
        migrations.AlterField(
            model_name='standings',
            name='contest_type',
            field=models.CharField(choices=[('AC', 'Acm'), ('AO', 'Acm competition'), ('OL', 'Olympiad'), ('BS', 'Battleship'), ('BT', 'Blitz')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='standingssheetexport',
            name='mark_func',
            field=models.TextField(default='\ndef calc_marks_v1(\n    user_scores, # 2d array containing all scores for users\n    contest_info, # contest info from algocode admin\n):\n    return [0] * len(user_scores)\n\nmarks = calc_marks_v1(user_scores, contest_info)\n'),
        ),
    ]
