# Generated by Django 4.2.1 on 2023-11-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_contest_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='standings',
            name='enable_upsolving',
            field=models.BooleanField(default=False),
        ),
    ]
